<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">#500 Error</h3>
	</div>
	<div class="panel-body">
		<h1>Application Error</h1>
		<p>The server encountered an internal error or misconfiguration and
			was unable to complete your request.</p>
		<p>Please contact the server administrator, admin@example.com and
			inform them of the time the error occurred, and anything you might
			have done that may have caused the error.</p>
		<p>More information about this error may be available in the server
			error log.</p>
		<p>Additionally, a 500 Internal Server Error error was encountered
			while trying to use an ErrorDocument to handle the request.</p>
	</div>
</div>