<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Delay</h3>
	</div>
	<div class="panel-body">
		<p>The test is looking for this phrase: Hello, World!. The next part
			of this page will load after 2 seconds!</p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Lorem Ipsum</h3>
	</div>
	<div class="panel-body" id="lorem"></div>
</div>

<script type="text/javascript">
setTimeout("jQuery.ajax({ url: '/site/lorem', success: function(data) { jQuery('#lorem').html(data);}});", 2000);
</script>

<div class="panel panel-default">
	<div class="panel-heading">
	<h3 class="panel-title">Selenium Code</h3>
	</div>
	<div class="panel-body">
	<ul class="list-unstyled">
	<li>open('<?php echo $this->serverUrl() ?>/site/view/owner/<?php echo $this->user ?>')</li>
	<li>WaitForNoRequest(3000)</li>
	<li>AssertTextPresent('Hello, World!')</li>
	<li>AssertTextPresent('persecuti delicatissimi')</li>
	</ul>
	</div>
</div>