<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Hosts &amp; Zones</h3>
	</div>
	<div class="panel-body">
		<p>
The test is looking for this phrase: Hello, World!. A 3rd Party video from YouTube will also be included.
		</p>
		<div>
<!--
<object width="560" height="340">
	<param name="movie" value="http://www.youtube.com/v/xaPepCVepCg&hl=en_US&fs=1&rel=0" />
	<param name="allowFullScreen" value="true" />
	<param name="allowscriptaccess" value="always" />
	<embed src="http://www.youtube.com/v/xaPepCVepCg&hl=en_US&fs=1&rel=0" type="application/x-shockwave-flash" width="560" height="340" />
</object>
-->
			<div class="embed-responsive embed-responsive-16by9">
      	<iframe class="embed-responsive-item" src="//www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen=""></iframe>
    	</div>
		</div>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Selenium Code</h3>
	</div>
	<div class="panel-body">
		<ul class="list-unstyled">
			<li>open('<?php echo $this->serverUrl() ?>/site/view/owner/<?php echo $this->user ?>')</li>
			<li>AssertTextPresent('Hello, World!')</li>
		</ul>
	</div>
</div>
