<div class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">JS Error</h3>
	</div>
	<div class="panel-body">
		<p>The test is looking for this phrase: Hello, World! but there is now
			a JavaScript error.</p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
	<h3 class="panel-title">Selenium Code</h3>
	</div>
	<div class="panel-body">
	<ul class="list-unstyled">
	<li>open('<?php echo $this->serverUrl() ?>/site/view/owner/<?php echo $this->user ?>')</li>
	<li>AssertTextPresent('Hello, World!')</li>
	</ul>
	</div>
</div>