<div class="panel panel-danger">
	<div class="panel-heading">
	<h3 class="panel-title">Validation Error</h3>
	</div>
	<div class="panel-body">The AssertTextPresent phrase is missing from this page.  This will generate an error and the measurement will fail.</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
	<h3 class="panel-title">Selenium Code</h3>
	</div>
	<div class="panel-body">
	<ul class="list-unstyled">
	<li>open('<?php echo $this->serverUrl() ?>/site/view/owner/<?php echo $this->user ?>')</li>
	<li>AssertTextPresent('Hello, World!')</li>
	</ul>
	</div>
</div>