<p>
The KITE script is looking for this phrase: Hello, World!.  Below is a 3rd Party video from YouTube.
</p>
<div>
<object width="560" height="340"><param name="movie" value="http://www.youtube.com/v/xaPepCVepCg&hl=en_US&fs=1&rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/xaPepCVepCg&hl=en_US&fs=1&rel=0" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="560" height="340"></embed></object>
</div>
