<ul class="nav nav-sidebar">
	<li><a href="#" onclick="setSiteState('validation_error');"><span class="glyphicon glyphicon-warning-sign"></span> Validation Error</a></li>
	<li><a href="#" onclick="setSiteState('css_error');"><span class="glyphicon glyphicon-warning-sign"></span> CSS Error</a></li>
	<li><a href="#" onclick="setSiteState('timeout');"><span class="glyphicon glyphicon-time"></span> Timeout Error</a></li>
	<li><a href="#" onclick="setSiteState('404');"><span class="glyphicon glyphicon-exclamation-sign"></span> #404 Error</a></li>
	<li><a href="#" onclick="setSiteState('500');"><span class="glyphicon glyphicon-ban-circle"></span> #500 Error</a></li>
</ul>
<ul class="nav nav-sidebar">
	<li><a href="#" onclick="setSiteState('delay');"><span class="glyphicon glyphicon-pause"></span> Content delay</a></li>
	<li><a href="#" onclick="setSiteState('hosts_and_zones');"><span class="glyphicon glyphicon-filter"></span> Hosts &amp; Zones</a></li>
</ul>
<ul class="nav nav-sidebar">
	<li><a href="#" onclick="setSiteState('chrome');"><span class="glyphicon glyphicon-globe"></span> Chrome</a></li>
	<li><a href="#" onclick="setSiteState('glimpse');"><span class="glyphicon glyphicon-user"></span> Glimpse</a></li>
</ul>
<ul class="nav nav-sidebar">
	<li><a href="#" onclick="setSiteState('default');"><span class="glyphicon glyphicon-flash"></span> Reset Site</a></li>
</ul>
