<?php
$server = $this->serverUrl();
header ("content-type: application/octet-stream");
header('Content-Disposition: attachment; filename="' . $this->user . '.kht"');

$mainScript = <<<EOF
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<script type="ApplicationPerspective" version="5.4.32.215" guid="976A838E-75BE-4F4B-8222-A2CFF4BD51AE" recorder="9.3.74.310" sav="2" xmlns="http://www.keynote.com/namespaces/tstp/script">
	<name>
		<![CDATA[Keynote - Breakable Site]]>
	</name>
	<description>
		<![CDATA[]]>
	</description>
	<settings>
		<s_timeout>45</s_timeout>
		<timeout>20</timeout>
		<browser customName="Microsoft Internet Explorer 7" type="Custom">
			<![CDATA[Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Keynote)]]>
		</browser>
		<download applets="1" images="1" scripts="1"/>
		<cookies enable="1"/>
		<errors all="0"/>
		<certificates/>
		<javascript_processing>
			<![CDATA[true]]>
		</javascript_processing>
		<stylesheet_parsing>
			<![CDATA[true]]>
		</stylesheet_parsing>
		<disable_element_download>0</disable_element_download>
	</settings>
	<actions>
		<action FrameErrorFatal="1" MetaErrorFatal="1">
			<name>
				<![CDATA[Keynote - Breakable Site]]>
			</name>
			<description>
				<![CDATA[Keynote - Breakable Site]]>
			</description>
			<step type="Navigate">
				<context window="0" frame="0"/>
				<parameter name="URL">
					<variable type="Static">
						<![CDATA[$server/site/view/owner/$this->user]]>
					</variable>
				</parameter>
			</step>
			<validation>
				<validate type="RequiredText" RegEx="0" element="HTML">
					<parameter name="Text">
						<variable type="Static">
							<![CDATA[Hello, World!]]>
						</variable>
					</parameter>
				</validate>
			</validation>
		</action>
	</actions>
	<info OS="5.1.2600 Service Pack 2" IE="7.0.5730.13" MSHTML="7.0.6000.16981" WinInet="7.0.6000.16981" WinHttp="5.1.2600.3619" MSXML6="6.20.2003.0">
		<ps e="0" d="0" s="0" el="0"/>
	</info>
</script>
EOF;
echo $mainScript;
?>
