<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="images/favicon.ico">
<title>Site Condition Creator - Catchpoint</title>
<!-- Bootstrap core CSS -->
<link href="/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="/css/scc.css" rel="stylesheet">
</head>

<body onload="$('#username').focus()">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a href="/"><img class="img-responsive" src="/images/logo.png"
					alt="Home"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
            <?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
            <li class="active"><a href="#"><span
							class="glyphicon glyphicon-user"></span> <?php echo $this->user ?></a></li>
					<li><a href="#" data-toggle="modal" data-target="#myModal"><span
							class="glyphicon glyphicon-cog"></span></a></li>
					<li><a href="/login/logout"><span
							class="glyphicon glyphicon-log-out"></span></a></li>
			<?php endif; ?>
          </ul>
			</div>
		</div>
	</div>

	<div class="container">
 	 <?php echo $this->layout()->content?>
    </div>

	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<form action="/settings/save" method="POST" role="form" id="settings">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
						</button>
						<h4 class="modal-title" id="myModalLabel">Pull API Settings</h4>
					</div>
					<div class="modal-body">
						<div class="form-group">
							<label for="key">Key</label>
							<input type="text" class="form-control" name="key" placeholder="Key">
						</div>
						<div class="form-group">
							<label for="secret">Secret</label>
							<input type="password" class="form-control" name="secret" placeholder="Secret">
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</body>
</html>
