<form role="form" method="POST" id="apiForm">
  <div class="form-group">
    <label for="url">https://io.catchpoint.com/ui/api/v1/</label>
    <input type="text" class="form-control" id="call" name="call" placeholder="API Call">
  </div>
  <button type="submit" id="submit" class="btn btn-primary">Submit</button>
</form>
<hr />
<pre id="apiResult"></pre>
<div id="pull">Retrieving data ... </div>
<script>
$(document).ready(function(){
    $("pre").hide();
    $("#pull").hide();
    $("#apiForm").submit(function(e){
        $("pre").hide();
        $("#pull").show();
        e.preventDefault();
        call = $("#call").val();
        $.ajax({
            type: "POST",
            url: "/pull/api/call/" + call,
            success: function(data){
                $("pre").show();
                $("#pull").hide();
                $("#apiResult").html(data);
            },
            error: function (request, status, error) {
                $("#pull").html(error);
            }
        })
    })
})
</script>
